### ISSUE TITLE
Why am I being ostracized?

### ISSUE THREAD

**Issue by Oxymoron290** [forgefed/forgefed#23]
>If you are experienced in writing specifications, you're also welcome to join the effort.

So if I have no experience, I am not welcomed in this project and barred from getting the experience?

**Comment by bill-auger** [comment]
regarding the license: the current license does not actually imply
open-ness at all; because it is a no-derivatives license - that is a
real problem and most want to see it changed to something truly open;
but that has not happened yet

regarding participation: it actually was discussed, whether or not to
close this github issue tracker; but it was decided to leave it open
and the github README clearly states:

```
Non-members may use the GitHub issue tracker or send us a mail ...
```

that sentence was added specifically to allow everyone to participate in
the discussions, both on github and on the mailing list; so absolutely
no one is being "ostracized" as this issue title so bluntly claims -
such confrontational insinuations are not productive - "you
catch more flies with honey than with vinegar", as the saying goes -
there are an open issues on this github issue tracker each corresponding
directly to each thread in the formal technical discussions -
absolutely every person on the planet is "encouraged" to express their
opinion; and there is nothing in the github README that would indicate
to the contrary

that README was written before the discussion began over six months ago
- for the most part, the discussion topics were exhausted some
months ago - it is quite clear now which features the spec needs to
accommodate; and the work remaining to be done is to codify the spec
and to work on implementations - the first reference implementation is
nearly completed now

regarding the specific language of the README itself: there is an
alternate repo on notabug that includes a revised README - i expect that
you will find the language in that one to be more plain and less
emotionally charged; but because of the current licensing situation,
the github repo has not been updated in some time

https://notabug.org/peers/forgefed/

**Comment by bill-auger** [comment]
oh, as an update for the benefit of github subscribers, i should also
add that a new IRC channel was created this week for the work related
to the reference implementation (#vervis on freenode) - that too, is
open to everyone

**Comment by Oxymoron290** [comment]
You mentioned several discussions and implied there are other issue trackers, repositories, etc. Can you provide links to useful, active, and open tools being used by this project? In addition to the one on notabug, I also found related information on dokk.org and framagit.org

Also, I can't tell or not, because the internet never does a good job and conveying feelings, but if you're peeved by my wording I apologize. I know you feel that it was confrontational and counter-productive, and from your perspective, I can respect that. However, from my perspective, as someone who has only known of this project for less than 48 hours, your response has been a treasure trove of information. So thank you for that. I look forward to participating further if you'll have me.

**Comment by bill-auger** [comment]
np bud - i have no desire to harp on any personal concerns on the
internet - i will just say that is was the specific words you used that
came across as inflammatory or more provocative than necessary -
the word "ostracized" is not even applicable in this context - what you
really meant was "why are inexperienced people excluded from the formal
technical discussion" (or better yet: "why are the formal technical
discussions conducted only by experienced people") - when stated that
way, the reason should be obvious; and is less likely to be interpreted
as an accusation

as i mentioned, most of the important technical discussions have run
their course; so the lack of activity on the mailing list is not an
indication of a lack of interest or progress - for the most part, there
is just not much to discuss at this stage, thats why the project may
appear to be dormant - the previous discussions are readable on the
framalistes website - that would be a great place to begin, catching up
on what was discussed already

https://framalistes.org/sympa/arc/git-federation

the most activity and discussion recently have been in the #peers IRC
channel on freenode and has been more general than technical - thats
essentially the only "community" channel for now - not for any
particular reason; but because folks in the peers group have been
interested in something like even before this github repo was created -
perhaps someday, forge-fed will have it's own website,, forum, or
fediverse instance, or whatever; but if you want to "connect" with an
interested community, thats probably all i can suggest for now

the #vervis channel i mentioned is more specifically for working on the
vervis forge, which we are treating as a reference implementation to
work the bugs out of the activity-pub messaging logistics - once it is
clear what the form of that looks like, some documentation can start
being written in tandem with the reference implementation

so, for now, neither the github repo or the notabug repo have much
in them; but that is where the written documentation and any support
libraries will eventually go - the two repos are out of sync now mostly
for the reason that there is not much concrete to show - it is hoped
that both repos will be mirrors in sync; but that is not very
important until once the artifacts begin taking shape

https://notabug.org/peers/forgefed/
