### ISSUE TITLE
Still "maintained"?

### ISSUE THREAD

**Issue by rugk** [forgefed/forgefed#28]
As it has been seen in https://github.com/forgefed/forgefed/issues/24 and https://github.com/forgefed/forgefed/pull/26 this repo seems to be dead.

So can someone please [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

If this is not possible, we can at least reflect the status in this issue or so.

**Comment by bill-auger** [comment]
this is demonstrating very inconsiderate netiquette - you made this same suggestion yesterday on another thread: "Add note about where to find up to date info #26" - that PR was opened originally to propose exactly the same suggestions that you repeated unnecessarily in that same thread yesterday, and are repeating again unnecessarily in this new post - the discussion within PR #26 clearly explains why your suggestions are not possible; but rather than read it, you declared your refusal to read it

luckily, none of these suggestions are necessary - for one thing, the effort is not "dead" - the focus has simply moved to other venues - this git repo does not represent any effort, as there is nothing in it to archive, except for a license that was unanimously decided would not be used - so the word "unmaintained" do not even apply; because nothing was ever added to the repo in the first place that would need to be maintained - the most relevance that this github project ever had, was as a discussion board, for about one week before it was decided that a mailing list should be created for some cross-project exploratory discussions

after those exploratory discussions, the creator of this github project apparently lost interest - but again, that not a big problem; becuase nothing tangible was ever associated with this github project - at the time that this github project; was created, it made no sense to use github or to have any code repo - discussion of federated forges had been ongoing for years prior to this github project; and all of the interesting discussions after that time, were on the mailing list, and still are readable in the archives, linked to on this main README - there really is nothing more that needs to be done to this github project unless koala returns and decides to bring it in sync with the others, destroy it, or assign more admins

anyone following links to this URL from other websites, have unfortunately found outdated information about the project - this github project is not the source of any outdated information, and the only thing that is slightly misleading is the unused repo - any corrections to be made are upon those external websites to simply update the info they are presenting about the forge-fed effort

**Comment by rugk** [comment]
> anyone following links to this URL from other websites, have unfortunately found outdated information about the project

Well… yes, that is the problem!

> he only thing that is slightly misleading is the unused repo

Yes!

So why, for all the sake of a simply edit, don't you just edit the Readme at least and explain that this repo is unused and people should go to https://github.com/forgefed/forge-fed/??
Is that soo hard?

> any corrections to be made, are upon those external websites to simply update the info they are presenting about the forge-fed effort

Sure, always blame others. That definitively helps.
E.g. gitea has a link to this repo in a _locked_ GitHub issue, so no one can even correct/comment it here.

**Comment by jkufner** [comment]
So there is https://github.com/forgefed/forge-fed/ and https://github.com/forgefed/forgefed/ ? Why?

**Comment by rugk** [comment]
Because it needs to be that™ wait… apparently…

**Comment by jaywink** [comment]
> So can someone please [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained

I think the only person who can do that disappeared from the face of the earth.

**Comment by bill-auger** [comment]
rugk -

!!! PLEASE READ THIS !!!

if it were possible to modify this repo, in any way, then your
suggestion would not be necessary - the repo would already be in
sync with the others, and PR #26 would not exist

that was explained in PR #26, and also in the sticky thread #24,
and also on this thread, when i answered you yesterday

but just to be clear: IT IS NOT POSSIBLE - thank you for your
suggestion but please stop suggesting it

**Comment by theodotos** [comment]
@yookoala Can you please archive this repo?

**Comment by bill-auger** [comment]
jkufner -

i created this post on the forum to answer your question

https://talk.feneas.org/t/why-is-the-forgefed-forgefed-github-repo-empty/161

**Comment by rugk** [comment]
> IT IS NOT POSSIBLE

Is it. You apparently have access to the issues, i.e. you can close them.,

As such, you also have git commit access to this repo.

**Because** on GitHub you cannot differentiate between these two things. You can only give access to the whole repo and this includes issues **and** repo access.

---

Also, you could:
* in any case just make a big new issue "THIS IS DEPRECATED" and keep it at the top of the issue list. Possibly pin and lock replies, so it stays at the top. Again: you can apparently do this.
* > https://talk.feneas.org/t/why-is-the-forgefed-forgefed-github-repo-empty/161
  
  still does not explain why you cannot archive this repo

**Comment by ppwfx** [comment]
🍿

**Comment by nightpool** [comment]
Only @yookoala can archive the repository, which requires admin access, but we can and should definitely update the README

**Comment by bill-auger** [comment]
the point i was trying to make is that "THIS IS DEPRECATED" makes no sense - there is nothing in this repo to deprecate - it was never used - only this bug tracker was ever used - it was used as a discussion forum, and the information that it contains is fully up to date - there already is a "sticky" issue named: "Current Status" - that can be used to note anything that has changed

the essential message of: "this is deprecated" in this context, would be more like: "this github project is abandoned or is not longer used"; but that is not correct - the bug tracker can still be used as a discussion forum; which is all that this github project ever was - i.e. nothing has changed regarding what this github project is actually used for, since it was created

of those who have commented in this issue: jkufner, jaywink, theodotos, ppwfx, and nightpool all have the same permission set as i do - i have not tried to push to this repo; but on the PR i see "You’re not authorized to merge this pull request." - i assume that means i do not have write access, and i assume the same is true for everyone else - it appears to be a "protected branch", which is a feature that only an admin can change; and koala is the only admin - i think that prevent force pushes, and what is needed to make this repo useful is a force push of the other repo https://github.com/forgefed/forgefed/onto this one

**Comment by nightpool** [comment]
ah, my mistake, I had only seen "protected branches" used in modes that required approved PRs before merging, but it appears that they can be set up to fully prevent merging from non-admin collaborators, as this one is. (I tested by approving the open PR, although it still contains incorrect information and probably shouldn't be merged as-is)
